import streamlit as st
import pandas as pd
import plotly.express as px
import requests
from datetime import date
import google.generativeai as genai
import os

st.title("LLM Insights")
st.write("This page uses a pre-trained large language model to interpret and summarize the API data with natural language.")


# ✅ Configure Streamlit page
st.set_page_config(page_title="AI Weather Forecaster", page_icon="🤖", layout="wide")

st.title("🤖 AI Weather Forecaster")
st.caption("Get a personalized weather forecast generated by Google Gemini based on Open‑Meteo data.")


with st.sidebar:
    st.header("Inputs")
    city = st.text_input("City / Place", value="Atlanta")
    forecast_date = st.date_input("Forecast Date", value=date.today())
    units = st.radio("Units", ["Metric (°C, m/s)", "Imperial (°F, mph)"], index=1)
    style = st.selectbox("Forecast Style", ["Friendly", "Professional", "Funny", "Detailed"])
    extra_notes = st.text_area("Add extra context (optional)", placeholder="e.g., outdoor plans, travel tips")


if forecast_date < date.today():
    st.warning("Please select today or a future date for forecast.")
    st.stop()

 
geo_url = "https://geocoding-api.open-meteo.com/v1/search"
r = requests.get(geo_url, params={"name": city, "count": 1, "language": "en", "format": "json"})
if r.status_code != 200 or r.json().get("results") is None:
    st.error("Could not find that location. Try another city.")
    st.stop()

loc = r.json()["results"][0]
lat, lon = loc["latitude"], loc["longitude"]
resolved_name = f'{loc["name"]}, {loc.get("admin1","")}, {loc.get("country","")}'


temp_unit = "fahrenheit" if "Imperial" in units else "celsius"
wind_unit = "mph" if "Imperial" in units else "ms"

weather_url = "https://api.open-meteo.com/v1/forecast"
params = {
    "latitude": lat,
    "longitude": lon,
    "hourly": ["temperature_2m", "wind_speed_10m", "precipitation"],
    "start_date": forecast_date.isoformat(),
    "end_date": forecast_date.isoformat(),
    "temperature_unit": temp_unit,
    "wind_speed_unit": wind_unit,
    "timezone": "auto",
}
wr = requests.get(weather_url, params=params)
wr.raise_for_status()
data = wr.json()

hourly = data["hourly"]
df = pd.DataFrame({
    "time": pd.to_datetime(hourly["time"]),
    "temperature": hourly["temperature_2m"],
    "wind_speed": hourly["wind_speed_10m"],
    "precipitation": hourly["precipitation"],
}).set_index("time")


high_temp = df["temperature"].max()
low_temp = df["temperature"].min()
avg_wind = df["wind_speed"].mean()
total_precip = df["precipitation"].sum()


fig = px.line(df.reset_index(), x="time", y="temperature",
              title=f"Hourly Temperature for {resolved_name} on {forecast_date}",
              labels={"temperature": f"Temperature ({'°F' if 'Imperial' in units else '°C'})"})
st.plotly_chart(fig, use_container_width=True)


st.subheader("Forecast Summary")
st.write(f"**Location:** {resolved_name}")
st.write(f"**Date:** {forecast_date}")
st.write(f"High: {high_temp:.1f}, Low: {low_temp:.1f}, Avg Wind: {avg_wind:.1f}, Total Precip: {total_precip:.1f}")


genai.configure(api_key=os.getenv("GEMINI_API_KEY"))  model = genai.GenerativeModel("gemini-pro")


prompt = f"""
Generate a {style.lower()} weather forecast for {resolved_name} on {forecast_date}.
Data:
- High Temp: {high_temp:.1f} {'°F' if 'Imperial' in units else '°C'}
- Low Temp: {low_temp:.1f} {'°F' if 'Imperial' in units else '°C'}
- Avg Wind: {avg_wind:.1f} {'mph' if 'Imperial' in units else 'm/s'}
- Total Precipitation: {total_precip:.1f} mm
Extra context: {extra_notes if extra_notes else 'None'}
Make it engaging and easy to understand.
"""


if st.button("Generate AI Forecast"):
    with st.spinner("Generating forecast..."):
        response = model.generate_content(prompt)
        st.success("Here’s your AI-generated forecast:")
        st.write(response.text)

